echo "Ensure DNS resolver configuration is properly symlinked"
echo "Ensuring consistent DNS configuration and user config protection..."

# (Respects User Config)
# - If 'dns=systemd-resolved' is already set (even in a custom user file), we do nothing.
# - Only injects configuration if the system is currently unconfigured/broken.
if command -v NetworkManager >/dev/null; then
    NM_CONF_DIR="/etc/NetworkManager/conf.d"
    
    # Ensure directory exists (handles minimal installs)
    sudo mkdir -p "$NM_CONF_DIR"

    # Check if the configuration already exists anywhere in the directory
    if ! grep -rq "^dns=systemd-resolved" "$NM_CONF_DIR" 2>/dev/null; then
        echo "Injecting default DNS backend for NetworkManager..."
        
        # Use '10-' prefix (lower priority) so users can easily override it 
        # with a '99-user.conf' if they wish to use a different backend later.
        echo -e "# Auto-generated by Omarchy setup.\n[main]\ndns=systemd-resolved" | sudo tee "$NM_CONF_DIR/10-omarchy-dns.conf" >/dev/null
    else
        echo "Existing valid NetworkManager configuration detected. Respecting user settings."
    fi
fi

# - Uses 'ln --backup=numbered': Native atomic operation.
# - If /etc/resolv.conf is a static file (user data), it is RENAMED (e.g., resolv.conf.~1~)
#   instead of being silently overwritten.
sudo ln -sf --backup=numbered /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
